parameter_defaults:
  CephAnsiblePlaybookVerbosity: 3
  CephAnsibleEnvironmentVariables:
    ANSIBLE_SSH_RETRIES: '6'
    DEFAULT_FORKS: '25'
  CephConfigOverrides:
    log_to_file: true
    osd_pool_default_size: 3
    osd_pool_default_min_size: 2
    mon_max_pg_per_osd: 1000
    max_open_files: 131072
    osd_recovery_op_priority: 3
    osd_recovery_max_active: 3
    osd_max_backfills: 1
    osd_pool_default_pg_num: 32
    osd_pool_default_pgp_num: 32
  CephAnsibleExtraConfig:
    is_hci: true
    hci_safety_factor: 0
    osd_memory_target: 5179869184
    ceph_rgw_docker_memory_limit: "3096m"
    ceph_rgw_docker_cpu_limit: 2
    ceph_mon_docker_memory_limit: "2048m"
    ceph_mon_docker_cpu_limit: 1
    ceph_mgr_docker_memory_limit: "3333m"
    ceph_mgr_docker_cpu_limit: 1
    ceph_mds_docker_memory_limit: "2222m"
    ceph_mds_docker_cpu_limit: 4
    ceph_osd_docker_cpu_limit: 2
    grafana_container_cpu_cores: 2
    prometheus_container_cpu_cores: 2
    alertmanager_container_cpu_cores: 2
    grafana_container_memory: 4
    prometheus_container_memory: 4
    alertmanager_container_memory: 4



    crush_rule_config: true
    create_crush_tree: true
    crush_rules:
      - name: HDD
        root: default
        type: host
        class: hdd
        default: true
  CephAnsibleDisksConfig:
    osd_scenario: collocated
    devices:
      - /dev/vdb
      - /dev/vdc
  CephPools:
    - {"name": backups, "pg_num": 64, "pgp_num": 64, "application": rbd}
    - {"name": volumes, "pg_num": 60, "pgp_num": 60, "application": rbd}
    - {"name": vms, "pg_num": 65, "pgp_num": 65, "application": rbd}
    - {"name": images, "pg_num": 32, "pgp_num": 32, "application": rbd}
    - {"name": cephfs_data, "pg_num": 32, "pgp_num": 32, "application": cephfs}
    - {"name": cephfs_metadata, "pg_num": 32, "pgp_num": 32, "application": cephfs}
    - {"name": .rgw.root, "pg_num": 32, "pgp_num": 32, "application": rgw}
    - {"name": default.rgw.control, "pg_num": 32, "pgp_num": 32, "application": rgw}
    - {"name": default.rgw.meta, "pg_num": 32, "pgp_num": 32, "application": rgw}
    - {"name": default.rgw.log, "pg_num": 32, "pgp_num": 32, "application": rgw}
